services:
  orangepi-edge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orangepi-edge
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
